version: "3.9"

services:
  service:
    build:
      context: .
      dockerfile: Dockerfile.service
    container_name: go-heartbeat-service
    ports:
      - "8080:8080"

  client1:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: go-heartbeat-client1
    depends_on:
      - service

  client2:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: go-heartbeat-client2
    depends_on:
      - service
