FROM golang:1.23-alpine as builder

WORKDIR /app

COPY src/client.go .

RUN go mod init client && go mod tidy
RUN go build -o client .

FROM alpine:3.18

RUN apk add --no-cache libc6-compat

COPY --from=builder /app/client /client

CMD ["/client"]