FROM golang:1.23-alpine as builder

WORKDIR /app

COPY src/service.go .

RUN go mod init service && go mod tidy
RUN go build -o service .

FROM alpine:3.18

RUN apk add --no-cache libc6-compat

COPY --from=builder /app/service /service

CMD ["/service"]