version: "3.9"

services:
  mqtt:
    image: eclipse-mosquitto:2.0.20
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  service:
    build:
      context: .
      dockerfile: Dockerfile.service
    container_name: py-heartbeat-service
    depends_on:
      - mqtt
    environment:
      - BROKER=mqtt
      - PORT=8883
      - PYTHONUNBUFFERED=1 # so that print statements appear on the terminal

  client1:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: py-heartbeat-client1
    depends_on:
      - mqtt
      - service
    environment:
      - BROKER=mqtt
      - PORT=8883
      - PYTHONUNBUFFERED=1 # so that print statements appear on the terminal
