# Use an official Python runtime as a base image
FROM python:3.13-slim

# Set the working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY src/service.py .

# Expose the MQTT port
EXPOSE 8883

# Run the service
CMD ["python", "service.py"]
